qlib_init:
  provider_uri: ~/.qlib/qlib_data/cn_data
  region: cn
market: all
benchmark: SH000300
data_handler_config: &id001
  start_time: 2020-01-01
  end_time: '2025-01-06'
  fit_start_time: 2020-01-01
  fit_end_time: 2022-12-31
  instruments: all
port_analysis_config: &id002
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 50
      n_drop: 2
      hold_thresh: 2
  backtest:
    start_time: '2025-01-02'
    end_time: '2025-01-06'
    account: 50000
    benchmark: SH000300
    exchange_kwargs:
      limit_threshold: 0.095
      deal_price: close
      open_cost: 0.0005
      close_cost: 0.0015
      min_cost: 5
  executor:
    class: SimulatorExecutor
    module_path: qlib.backtest.executor
    kwargs:
      time_per_step: day
      generate_portfolio_metrics: true
      verbose: true
task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.0421
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
      num_boost_round: 2000
      early_stopping_rounds: 100
      verbose_eval: 50
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *id001
      segments:
        train:
        - 2020-01-01
        - 2022-12-31
        valid:
        - 2023-01-01
        - 2024-12-31
        test:
        - '2025-01-02'
        - '2025-01-06'
  record:
  - class: SignalRecord
    module_path: qlib.workflow.record_temp
    kwargs:
      model: <MODEL>
      dataset: <DATASET>
  - class: SigAnaRecord
    module_path: qlib.workflow.record_temp
    kwargs:
      ana_long_short: false
      ann_scaler: 252
  - class: PortAnaRecord
    module_path: qlib.workflow.record_temp
    kwargs:
      config: *id002
